// Weapon definitions. `tier` gates the shop to the matching base tier.
// `ammo` null means a melee weapon with no magazine.

export const WEAPONS = {
  bat: {
    id: "bat",
    name: "Wooden Bat",
    tier: 0,
    price: 0,
    melee: true,
    damage: 18,
    fireRate: 1.55,
    mag: Infinity,
    magGrowth: 0,
    reload: 0,
    range: 2.7,
    spread: 0,
    pellets: 1,
    ammo: null,
    headshot: 1.35,
    crit: 0.04,
    armorPierce: false,
    fullAuto: false,
    blurb: "A split fence post. Honest work.",
  },
  pistol: {
    id: "pistol",
    name: "Pistol",
    tier: 0,
    price: 500,
    melee: false,
    damage: 20,
    fireRate: 3.1,
    mag: 12,
    magGrowth: 2,
    reload: 1.15,
    range: 42,
    spread: 0.012,
    pellets: 1,
    ammo: "pistol",
    starterAmmo: 48,
    headshot: 1.9,
    crit: 0.06,
    armorPierce: false,
    fullAuto: false,
    blurb: "The first sidearm that makes a shambler hesitate.",
  },
  shotgun: {
    id: "shotgun",
    name: "Shotgun",
    tier: 1,
    price: 1500,
    melee: false,
    damage: 9,
    fireRate: 0.95,
    mag: 6,
    magGrowth: 1,
    reload: 1.85,
    range: 16,
    spread: 0.11,
    pellets: 7,
    ammo: "shell",
    starterAmmo: 24,
    headshot: 1.4,
    crit: 0.05,
    armorPierce: false,
    fullAuto: false,
    blurb: "Ugly at range. Decisive in a doorway.",
  },
  smg: {
    id: "smg",
    name: "SMG",
    tier: 2,
    price: 3000,
    melee: false,
    damage: 11,
    fireRate: 10,
    mag: 30,
    magGrowth: 4,
    reload: 1.45,
    range: 28,
    spread: 0.048,
    pellets: 1,
    ammo: "pistol",
    starterAmmo: 90,
    headshot: 1.55,
    crit: 0.05,
    armorPierce: false,
    fullAuto: true,
    blurb: "Burns ammunition to keep runners off the gate.",
  },
  rifle: {
    id: "rifle",
    name: "Assault Rifle",
    tier: 2,
    price: 7500,
    melee: false,
    damage: 22,
    fireRate: 7.2,
    mag: 30,
    magGrowth: 4,
    reload: 1.6,
    range: 52,
    spread: 0.02,
    pellets: 1,
    ammo: "rifle",
    starterAmmo: 120,
    headshot: 1.8,
    crit: 0.07,
    armorPierce: false,
    fullAuto: true,
    blurb: "The backbone weapon of a stone fort.",
  },
  sniper: {
    id: "sniper",
    name: "Sniper Rifle",
    tier: 3,
    price: 12000,
    melee: false,
    damage: 92,
    fireRate: 0.75,
    mag: 5,
    magGrowth: 1,
    reload: 2.15,
    range: 92,
    spread: 0.002,
    pellets: 1,
    ammo: "rifle",
    starterAmmo: 30,
    headshot: 3.1,
    crit: 0.12,
    armorPierce: true,
    fullAuto: false,
    blurb: "One calm shot. Armor does not enjoy it.",
  },
  lmg: {
    id: "lmg",
    name: "LMG",
    tier: 3,
    price: 14000,
    melee: false,
    damage: 16,
    fireRate: 12,
    mag: 80,
    magGrowth: 10,
    reload: 3.1,
    range: 46,
    spread: 0.04,
    pellets: 1,
    ammo: "rifle",
    starterAmmo: 200,
    headshot: 1.45,
    crit: 0.04,
    armorPierce: false,
    fullAuto: true,
    blurb: "A portable turret with a worse personality.",
  },
  advrifle: {
    id: "advrifle",
    name: "Advanced Rifle",
    tier: 4,
    price: 22000,
    melee: false,
    damage: 28,
    fireRate: 8,
    mag: 36,
    magGrowth: 4,
    reload: 1.45,
    range: 58,
    spread: 0.014,
    pellets: 1,
    ammo: "rifle",
    starterAmmo: 140,
    headshot: 2,
    crit: 0.09,
    armorPierce: true,
    fullAuto: true,
    blurb: "Fort Halden issue. Ignores cheap plate.",
  },
  rocket: {
    id: "rocket",
    name: "Rocket Launcher",
    tier: 4,
    price: 25000,
    melee: false,
    projectile: true,
    damage: 190,
    fireRate: 0.4,
    mag: 1,
    magGrowth: 0,
    reload: 2.35,
    range: 54,
    spread: 0.01,
    pellets: 1,
    splash: 4.2,
    ammo: "heavy",
    starterAmmo: 8,
    headshot: 1,
    crit: 0.02,
    armorPierce: true,
    fullAuto: false,
    blurb: "Clears a packed gate. Mind your own walls.",
  },
  energy: {
    id: "energy",
    name: "Energy Rifle",
    tier: 5,
    price: 50000,
    requires: "lab",
    melee: false,
    damage: 34,
    fireRate: 6.5,
    mag: 40,
    magGrowth: 6,
    reload: 1.35,
    range: 64,
    spread: 0.01,
    pellets: 1,
    ammo: "energy",
    starterAmmo: 120,
    headshot: 2.1,
    crit: 0.1,
    armorPierce: true,
    fullAuto: true,
    blurb: "Blackglass cells. The beam smells like rain on hot stone.",
  },
  plasma: {
    id: "plasma",
    name: "Plasma Cannon",
    tier: 5,
    price: 75000,
    requires: "lab",
    melee: false,
    projectile: true,
    damage: 78,
    fireRate: 1.15,
    mag: 8,
    magGrowth: 2,
    reload: 2,
    range: 48,
    spread: 0.02,
    pellets: 1,
    splash: 2.8,
    ammo: "energy",
    starterAmmo: 40,
    headshot: 1.2,
    crit: 0.06,
    armorPierce: true,
    fullAuto: false,
    blurb: "Endgame. Everything in the splash regrets it.",
  },
};

export const WEAPON_ORDER = [
  "bat", "pistol", "shotgun", "smg", "rifle", "sniper", "lmg", "advrifle", "rocket", "energy", "plasma",
];

export const MAX_WEAPON_LEVEL = 5;

// Level is 1-based. Each rank is a visible jump, not a rounding error.
export function computeWeaponStats(def, level, mods) {
  const lv = Math.max(0, (level || 1) - 1);
  const m = mods || {};
  const magBase = def.mag === Infinity ? Infinity : def.mag + (def.magGrowth || 0) * lv;
  return {
    damage: def.damage * (1 + 0.18 * lv) * (m.damage || 1),
    fireRate: def.fireRate * (1 + 0.045 * lv) * (m.fireRate || 1),
    mag: magBase === Infinity ? Infinity : Math.round(magBase),
    reload: def.reload * Math.max(0.45, 1 - 0.06 * lv) * (m.reload || 1),
    range: def.range * (1 + 0.03 * lv),
    spread: def.spread * Math.max(0.25, 1 - 0.07 * lv) * (m.spread || 1),
    pellets: def.pellets || 1,
    crit: (def.crit || 0.05) + 0.012 * lv + (m.crit || 0),
    headshot: def.headshot || 1.8,
    splash: def.splash || 0,
    armorPierce: !!def.armorPierce,
    melee: !!def.melee,
    projectile: !!def.projectile,
    fullAuto: !!def.fullAuto,
    ammo: def.ammo,
  };
}

export function upgradeCost(def, nextLevel) {
  const base = Math.max(80, Math.round((def.price || 200) * 0.32));
  return {
    gold: Math.round(base * Math.pow(1.72, nextLevel - 2)),
    parts: nextLevel + 1,
  };
}
